# Generated by Django 5.0.6 on 2025-01-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_dailyword_guesses_delete_word"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailyword",
            old_name="word",
            new_name="en_word",
        ),
    ]
