# Generated by Django 5.0.6 on 2025-01-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_dailyword_fa_word"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bale_id", models.CharField(max_length=40)),
                ("lang", models.CharField(default="english", max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name="guesses",
            name="lang",
            field=models.CharField(default="english", max_length=10),
            preserve_default=False,
        ),
    ]
