# Generated by Django 5.0.6 on 2025-01-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_users_guesses_lang"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="id",
        ),
        migrations.AlterField(
            model_name="users",
            name="bale_id",
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
